//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zhihu.Common.Rtf {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zhihu.Common.Rtf.Strings", typeof(Strings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unsupported text in color table: &apos;{0}&apos;.
        /// </summary>
        internal static string ColorTableUnsupportedText {
            get {
                return ResourceManager.GetString("ColorTableUnsupportedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to duplicate font id &apos;{0}&apos;.
        /// </summary>
        internal static string DuplicateFont {
            get {
                return ResourceManager.GetString("DuplicateFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to document has not contents.
        /// </summary>
        internal static string EmptyDocument {
            get {
                return ResourceManager.GetString("EmptyDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid font size, must be in the range [1..0xFFFF], but is {0}.
        /// </summary>
        internal static string FontSizeOutOfRange {
            get {
                return ResourceManager.GetString("FontSizeOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}:{1} x {2}].
        /// </summary>
        internal static string ImageFormatText {
            get {
                return ResourceManager.GetString("ImageFormatText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to charset may not be negative but is {0}.
        /// </summary>
        internal static string InvalidCharacterSet {
            get {
                return ResourceManager.GetString("InvalidCharacterSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to code page may not be negative but is {0}.
        /// </summary>
        internal static string InvalidCodePage {
            get {
                return ResourceManager.GetString("InvalidCodePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid color component, must be in the range [0..255], but is {0}.
        /// </summary>
        internal static string InvalidColor {
            get {
                return ResourceManager.GetString("InvalidColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid default font id &apos;{0}&apos;, only the following fonts are available (yet): {1}.
        /// </summary>
        internal static string InvalidDefaultFont {
            get {
                return ResourceManager.GetString("InvalidDefaultFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to first tag in document is not {0}.
        /// </summary>
        internal static string InvalidDocumentStartTag {
            get {
                return ResourceManager.GetString("InvalidDocumentStartTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid font size.
        /// </summary>
        internal static string InvalidFontSize {
            get {
                return ResourceManager.GetString("InvalidFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid generator group: {0}.
        /// </summary>
        internal static string InvalidGeneratorGroup {
            get {
                return ResourceManager.GetString("InvalidGeneratorGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to desiredHeight must be &gt; 0 but is {0}.
        /// </summary>
        internal static string InvalidImageDesiredHeight {
            get {
                return ResourceManager.GetString("InvalidImageDesiredHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image desiredWidth must be &gt; 0 but is {0}.
        /// </summary>
        internal static string InvalidImageDesiredWidth {
            get {
                return ResourceManager.GetString("InvalidImageDesiredWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image height must be &gt; 0 but is {0}.
        /// </summary>
        internal static string InvalidImageHeight {
            get {
                return ResourceManager.GetString("InvalidImageHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scaleHeightPercent must be &gt; 0 but is {0}.
        /// </summary>
        internal static string InvalidImageScaleHeight {
            get {
                return ResourceManager.GetString("InvalidImageScaleHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image scaleWidthPercent must be &gt; 0 but is {0}.
        /// </summary>
        internal static string InvalidImageScaleWidth {
            get {
                return ResourceManager.GetString("InvalidImageScaleWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image width must be &gt; 0 but is {0}.
        /// </summary>
        internal static string InvalidImageWidth {
            get {
                return ResourceManager.GetString("InvalidImageWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Init: illegal state for group: &apos;{0}&apos;.
        /// </summary>
        internal static string InvalidInitGroupState {
            get {
                return ResourceManager.GetString("InvalidInitGroupState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Init: illegal state for tag &apos;{0}&apos;.
        /// </summary>
        internal static string InvalidInitTagState {
            get {
                return ResourceManager.GetString("InvalidInitTagState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Init: illegal state for text: &apos;{0}&apos;.
        /// </summary>
        internal static string InvalidInitTextState {
            get {
                return ResourceManager.GetString("InvalidInitTextState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to illegal state: cannot pop text format from empty stack.
        /// </summary>
        internal static string InvalidTextContextState {
            get {
                return ResourceManager.GetString("InvalidTextContextState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BeginDocument.
        /// </summary>
        internal static string LogBeginDocument {
            get {
                return ResourceManager.GetString("LogBeginDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndDocument.
        /// </summary>
        internal static string LogEndDocument {
            get {
                return ResourceManager.GetString("LogEndDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InsertBreak: {0}.
        /// </summary>
        internal static string LogInsertBreak {
            get {
                return ResourceManager.GetString("LogInsertBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InsertChar: {0}.
        /// </summary>
        internal static string LogInsertChar {
            get {
                return ResourceManager.GetString("LogInsertChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InsertImage: {0}: {1} x {2}, desired: {3} x {4}, scaled: {5}% x {6}%, {8} bytes.
        /// </summary>
        internal static string LogInsertImage {
            get {
                return ResourceManager.GetString("LogInsertImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InsertText: &apos;{0}&apos; with format [{1}].
        /// </summary>
        internal static string LogInsertText {
            get {
                return ResourceManager.GetString("LogInsertText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        internal static string LogOverflowText {
            get {
                return ResourceManager.GetString("LogOverflowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to first element in document is not a tag.
        /// </summary>
        internal static string MissingDocumentStartTag {
            get {
                return ResourceManager.GetString("MissingDocumentStartTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unspecified RTF version.
        /// </summary>
        internal static string MissingRtfVersion {
            get {
                return ResourceManager.GetString("MissingRtfVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to undefined color index: {0}.
        /// </summary>
        internal static string UndefinedColor {
            get {
                return ResourceManager.GetString("UndefinedColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to undefined font: {0}.
        /// </summary>
        internal static string UndefinedFont {
            get {
                return ResourceManager.GetString("UndefinedFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unsupported RTF version: {0}.
        /// </summary>
        internal static string UnsupportedRtfVersion {
            get {
                return ResourceManager.GetString("UnsupportedRtfVersion", resourceCulture);
            }
        }
    }
}
